/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fff8f3',
        'surface-dim': '#e1d9d0',
        'surface-bright': '#fff8f3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2e9',
        'surface-container': '#f5ede4',
        'surface-container-high': '#efe7de',
        'surface-container-highest': '#e9e1d8',
        'on-surface': '#1e1b16',
        'on-surface-variant': '#4e4639',
        'inverse-surface': '#34302a',
        'inverse-on-surface': '#f8efe6',
        'outline': '#7f7667',
        'outline-variant': '#d1c5b4',
        'surface-tint': '#775a19',
        'primary': '#775a19',
        'on-primary': '#ffffff',
        'primary-container': '#c5a059',
        'on-primary-container': '#4e3700',
        'inverse-primary': '#e9c176',
        'secondary': '#745853',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed7d0',
        'on-secondary-container': '#795c57',
        'tertiary': '#005faf',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#65a7ff',
        'on-tertiary-container': '#003b71',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fff8f3',
        'on-background': '#1e1b16',
        'surface-variant': '#e9e1d8',
        'alert-normal': '#689f38',
        'alert-watch': '#c5a059',
        'alert-act': '#ba1a1a',
      },
      fontFamily: {
        'space': ['"Space Grotesk"', 'sans-serif'],
        'manrope': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
